# Generated by Django 3.1.13 on 2021-08-31 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_clientuser_product_purchase_purchaseproductrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseproductrequest',
            old_name='quantity',
            new_name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseproductrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='client_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='users.clientuser'),
        ),
        migrations.AddField(
            model_name='purchaseproductrequest',
            name='product_price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
