# Generated by Django 3.1.13 on 2021-08-31 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210831_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='client_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='users.clientuser'),
        ),
        migrations.AlterField(
            model_name='purchaseproductrequest',
            name='product_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
