# Generated by Django 3.1.13 on 2021-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_purchaseproductrequest_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Activated'),
        ),
    ]
