# Generated by Django 3.1.13 on 2021-08-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_product_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_quantity',
            field=models.IntegerField(default=5, verbose_name='First Quantity'),
        ),
    ]
